# Generated by Django 3.1 on 2020-11-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20201019_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='c_co',
        ),
        migrations.RemoveField(
            model_name='city',
            name='c_co2',
        ),
        migrations.RemoveField(
            model_name='city',
            name='c_hc',
        ),
        migrations.RemoveField(
            model_name='city',
            name='c_no',
        ),
        migrations.AddField(
            model_name='city',
            name='max_c_co',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='city',
            name='max_c_co2',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='city',
            name='max_c_hc',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='city',
            name='max_c_no',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='city',
            name='min_c_co',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='city',
            name='min_c_co2',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='city',
            name='min_c_hc',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='city',
            name='min_c_no',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='accuracy',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='efco',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='efhc',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='efno',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='humidity',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='long',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='regmark',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='speed',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='temp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='city',
            name='wind_direction',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='wind_speed',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
    ]
