# Generated by Django 3.1 on 2020-11-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20201129_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='max_pm_25',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='city',
            name='min_pm_25',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
