# Generated by Django 3.1 on 2020-12-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20201129_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='max_pm_25',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='min_pm_25',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
